# -*- coding: utf-8 -*-

__all__ = (
	'ToHeaderName',
)


def ToHeaderName(key):
	return {
		'ACCEPT': 'Accept',
		'ACCEPT_CHARSET': 'Accept-Charset',
		'ACCEPT_ENCODING': 'Accept-Encoding',
		'ACCEPT_LANGUAGE': 'Accept-Language',
		'ACCEPT_RANGES': 'Accept-Ranges',
		'ACCESS_CONTROL_REQUEST_METHOD': 'Access-Control-Request-Method',
		'ACCESS_CONTROL_REQUEST_HEADERS': 'Access-Control-Request-Headers',
		'ACCESS_CONTROL_REQUEST_ORIGIN': 'Access-Control-Request-Origin',
		'ACCESS_CONTROL_REQUEST_CREDENTIALS': 'Access-Control-Request-Credentials',
		'ACCESS_CONTROL_EXPOSE_HEADERS': 'Access-Control-Expose-Headers',
		'ACCESS_CONTROL_MAX_AGE': 'Access-Control-Max-Age',
		'AGE': 'Age',  # Response header
		'ALLOW': 'Allow',  # Response header
		'AUTHORIZATION': 'Authorization',
		'CACHE_CONTROL': 'Cache-Control',
		'CONNECTION': 'Connection',
		'CONTENT_ENCODING': 'Content-Encoding',
		'CONTENT_LANGUAGE': 'Content-Language',
		'CONTENT_LENGTH': 'Content-Length',
		'CONTENT_LOCATION': 'Content-Location',
		'CONTENT_MD5': 'Content-MD5',
		'CONTENT_RANGE': 'Content-Range',
		'CONTENT_TYPE': 'Content-Type',
		'COOKIE': 'Cookie',
		'DATE': 'Date',
		'ETAG': 'ETag',
		'EXPECT': 'Expect',
		'EXPIRES': 'Expires',
		'FROM': 'From',
		'HOST': 'Host',
		'IF_MATCH': 'If-Match',
		'IF_MODIFIED_SINCE': 'If-Modified-Since',
		'IF_NONE_MATCH': 'If-None-Match',
		'IF_RANGE': 'If-Range',
		'IF_UNMODIFIED_SINCE': 'If-Unmodified-Since',
		'LAST_MODIFIED': 'Last-Modified',
		'LOCATION': 'Location',
		'MAX_FORWARDS': 'Max-Forwards',
		'ORIGIN': 'Origin',
		'PRAGMA': 'Pragma',
		'PROXY_AUTHENTICATE': 'Proxy-Authenticate',
		'PROXY_AUTHORIZATION': 'Proxy-Authorization',
		'RANGE': 'Range',
		'REFERER': 'Referer',
		'RETRY_AFTER': 'Retry-After',
		'SEC_WEBSOCKET_ACCEPT': 'Sec-WebSocket-Accept',
		'SEC_WEBSOCKET_EXTENSIONS': 'Sec-WebSocket-Extensions',
		'SEC_WEBSOCKET_KEY': 'Sec-WebSocket-Key',
		'SEC_WEBSOCKET_PROTOCOL': 'Sec-WebSocket-Protocol',
		'SEC_WEBSOCKET_VERSION': 'Sec-WebSocket-Version',
		'SERVER': 'Server',
		'SERVER_PROTOCOL': 'Server-Protocol',
		'SET_COOKIE': 'Set-Cookie',
		'TE': 'TE',
		'TRAILER': 'Trailer',
		'TRANSFER_ENCODING': 'Transfer-Encoding',
		'UPGRADE': 'Upgrade',
		'USER_AGENT': 'User-Agent',
		'VARY': 'Vary',
		'VIA': 'Via',
		'WARNING': 'Warning',
		'WWW_AUTHENTICATE': 'WWW-Authenticate'
	}.get(key.upper().replace('-', '_'), key)
