name: Create Tag
on:
  push:
    branches:
      - master
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Check if VERSION file changed
      id: check_version
      run: |
        # Get the latest commit where the VERSION file was changed
        VERSION_FILE="VERSION"
        LAST_CHANGE=$(git log -1 --format="%H" -- $VERSION_FILE)
        # Get the latest commit on master branch
        LATEST_COMMIT=$(git rev-parse HEAD)
        if [ "$LAST_CHANGE" != "$LATEST_COMMIT" ]; then
          echo "VERSION file was not changed in the latest commit. Skipping tag creation."
          echo "CREATE_TAG=false" >> $GITHUB_ENV
        else
          echo "VERSION file changed in the latest commit."
          echo "CREATE_TAG=true" >> $GITHUB_ENV
    - name: Create and push tag
      if: env.CREATE_TAG == 'true'
      run: |
        VERSION=$(cat VERSION)
        if [ ! -f VERSION ]; then
          echo "VERSION file not found!"
          exit 1
        fi
        if git rev-parse "$VERSION" >/dev/null 2>&1; then
          echo "Tag $VERSION already exists. Skipping."
          exit 0
        fi
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a "$VERSION" -m "Release - $VERSION"
        git push origin "release/$VERSION"
