name: Update VERSION
on:
  workflow_run:
    workflows: ["Test Liquirizia"]
    types:
      - completed
jobs:
  update-version:
    # Run only if tests succeeded and the target branch is master
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Update VERSION
        id: update_version
        run: |
          # Read the current branch name
          BRANCH_NAME=$(echo "${{github.event.workflow_run.head_branch}}" | tr '[:upper:]' '[:lower:]')
          # Read current version
          UPDATE=false
          OLD_VERSION=$(cat VERSION)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          # Determine update logic based on branch name
          if [[ "$BRANCH_NAME" =~ ^(bug|fix|hotfix) ]]; then
            PATCH=$((PATCH + 1))
            UPDATE=true
          elif [[ "$BRANCH_NAME" =~ ^(feature|feat) ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0  # Reset PATCH when MINOR is incremented
            UPDATE=true
          elif [[ "$BRANCH_NAME" =~ ^(release|rel) ]]; then
            cat "${{github.event.workflow_run.head_branch}}/VERSION" > VERSION
            echo "Using VERSION from release branch: $(cat VERSION)"
          else
            echo "No version update needed for branch: $BRANCH_NAME"
          fi
          # Write updated version back to file
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "$NEW_VERSION" > VERSION
          echo "Updated VERSION to $NEW_VERSION"
          echo "OLD_VERSION=$OLD_VERSION" > $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" > $GITHUB_ENV
          echo "UPDATE=$UPDATE" > $GITHUB_ENV
      - name: Commit and Push Updated VERSION
        if: env.UPDATE == 'true'
        run: |
          NEW_BRANCH="release/${{env.NEW_VERSION}}"
          git add VERSION
          git commit -m "Update VERSION from ${{env.OLD_VERSION}} to ${{env.NEW_VERSION}}"
          git push origin ${{github.ref}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branch: ${{github.ref}}
          title: "Release - ${{env.NEW_VERSION}}"
          body: "Update VERSION from ${{env.OLD_VERSION}} to ${{env.NEW_VERSION}}"
