name: Update VERSION
on:
  pull_request:
    types:
      - closed
jobs:
  update-version:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update VERSION
        run: |
          # Load current version
          if [ ! -f "VERSION" ]; then
            echo "VERSION file not found!"
            exit 1
          fi
          OLD_VERSION=$(cat VERSION)
          if ! [[ "$OLD_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "VERSION file has invalid format: $OLD_VERSION"
            echo "0.0.0" > VERSION
            OLD_VERSION="0.0.0"
          fi
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
          UPDATED=false
          echo "UPDATED=$UPDATED" >> $GITHUB_ENV
          # Determine update logic based on branch name
          if [[ "$BRANCH" =~ ^(bug|fix|hotfix) ]]; then
            PATCH=$((PATCH + 1))
            UPDATED=true
          elif [[ "$BRANCH" =~ ^(feature|feat) ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0  # Reset PATCH when MINOR is incremented
            UPDATED=true
          else
            echo "No version update needed for branch: $BRANCH"
            exit 1
          fi
          # Write updated version back to file
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "$NEW_VERSION" > VERSION
          echo "Updated VERSION from $OLD_VERSION to $NEW_VERSION"
          echo "OLD_VERSION=$OLD_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "UPDATED=$UPDATED" >> $GITHUB_ENV
      - name: Commit and Push Updated VERSION
        if: env.UPDATED == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add VERSION
          git commit -m "Update VERSION from $OLD_VERSION to $NEW_VERSION"
          git push origin ${{github.event.pull_request.base.ref}}
